# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7893fd8f8eaf701712d876c4acf8174cd800008ce766ffbdfe983006c3190c6826da478a669de1db592e9d3e4fdb1e7755ebe56efe5b53514e16f5092f2f6ddc

test:
  secret_key_base: 41ab2c9a8132346d724055b04ca7a00dc041cdc9e0ac549d1132e1983a7f81c3a4e23ca5d090bcd30bfd0c75f36255da9866ee5e5e7b0eee2f3935349e1926c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
